version: '3.8'

services:
  db:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - poke-data:/data/db

volumes:
  poke-data:
    external: false
